In [170]:
import pandas as pd 
df = pd.read_csv("Sales Data.csv")
data = pd.DataFrame(df)
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1236 entries, 0 to 1235
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Sales_ID     1236 non-null   int64
 1   Order_ID     1236 non-null   object
 2   Date_ID      1236 non-null   int64
 3   Customer_ID  1236 non-null   object
 4   Product_ID   1236 non-null   object
 5   Dealer_ID    1236 non-null   object
 6   Quantity     1152 non-null   float64
 7   Unit_Price   1152 non-null   float64
 8   Discount_%   1152 non-null   float64
 9   Sales        1152 non-null   float64
 10  Cost         1236 non-null   int64
 11  Profit       1236 non-null   int64
dtypes: float64(4), int64(4), object(4)
memory usage: 116.0+ KB

,Sales_ID,Date_ID,Quantity,Unit_Price,Discount_%,Sales,Cost,Profit
count,1236.000000,1.236000e+03,1152.000000,1152.000000,1152.000000,1152.000000,1236.000000,1236.000000
mean,598.649676,2.026067e+07,2.001736,98561.631944,7.230903,182731.119792,146207.022654,36551.755663
std,347.989117,3.462355e+02,0.815785,34657.109302,5.460273,102188.513328,81847.909662,20461.977415
min,1.000000,2.026010e+07,1.000000,42000.000000,0.000000,35700.000000,28560.000000,7140.000000
25%,297.750000,2.026033e+07,1.000000,67000.000000,0.000000,105375.000000,83910.000000,20977.500000
50%,598.500000,2.026070e+07,2.000000,99000.000000,5.000000,148600.000000,120000.000000,30000.000000
75%,898.250000,2.026093e+07,3.000000,128000.000000,10.000000,255250.000000,204000.000000,51000.000000
max,1200.000000,2.026123e+07,3.000000,160000.000000,15.000000,477000.000000,381600.000000,95400.000000

In [171]:
df.columns = df.columns.str.lower()
print(df.columns)

Index(['sales_id', 'order_id', 'date_id', 'customer_id', 'product_id',
       'dealer_id', 'quantity', 'unit_price', 'discount_%', 'sales', 'cost',
       'profit'],
      dtype='object')

In [172]:
df.isnull().sum()

sales_id        0
order_id        0
date_id         0
customer_id     0
product_id      0
dealer_id       0
quantity       84
unit_price     84
discount_%     84
sales          84
cost            0
profit          0
dtype: int64

In [173]:
import numpy as np
df = df.replace(['null', 'NULL', 'Null', np.nan],' ').fillna(0)

In [174]:
df.isnull().sum()

sales_id       0
order_id       0
date_id        0
customer_id    0
product_id     0
dealer_id      0
quantity       0
unit_price     0
discount_%     0
sales          0
cost           0
profit         0
dtype: int64

In [175]:
df = df.replace({'P003x':'P003',
                'D069x' :'D069'}
                ).fillna('NA')

In [176]:
df['product_id'] = df['product_id'].str.strip()
df['dealer_id'] = df['dealer_id'].str.strip()

In [177]:
df['customer_id'] = df['customer_id'].str.strip()

In [178]:
print(df.head(35))

    sales_id   order_id   date_id customer_id product_id dealer_id quantity  \
0          1   ORD00001  20261130       C0025       P003      D069      1.0
1          2   ORD00002  20260917       C0110       P002      D012      2.0
2          3   ORD00003  20260504       C0047       P018      D055      2.0
3          4   ORD00004  20260425       C0323       P021      D075      3.0
4          5   ORD00005  20260126       C0114       P002      D072      3.0
5          6   ORD00006  20260803       C0074       P018      D016      1.0
6          7   ORD00007  20260222       C0298       P019      D025      2.0
7          8   ORD00008  20261016       C0031       P020      D027      1.0
8          9   ORD00009  20260610       C0239       P019      D059      3.0
9         10   ORD00010  20260403       C0358       P025      D032      2.0
10        11   ORD00011  20260926       C0254       P029      D044      3.0
11        12    ORD0000  20261108        C002       P003      D069      2.0
12        13   ORD00013  20260319       C0251       P014      D006      1.0
13        14   ORD00014  20260624       C0356       P012      D077      1.0
14        15   ORD00015  20260205       C0048       P009      D061      3.0
15        16   ORD00016  20260201       C0375       P023      D040      3.0
16        17   ORD00017  20260526       C0367       P013      D045      3.0
17        18   ORD00018  20260328       C0313       P004      D064      2.0
18        19   ORD00019  20260308       C0379       P008      D051      1.0
19        20   ORD00020  20260327       C0230       P013      D071      2.0
20        21   ORD00021  20261009       C0143       P023      D054      1.0
21        22   ORD00022  20260429       C0078       P003      D023      3.0
22        23   ORD00023  20260107       C0249       P027      D076      1.0
23        24   ORD00024  20260103       C0075       P014      D069      2.0
24        25   ORD00025  20260306       C0354       P028      D066      3.0
25        26   ORD00026  20260822       C0400       P028      D072      3.0
26        27   ORD00027  20260721       C0054       P016      D052      2.0
27        28   ORD00028  20260417       C0226       P006      D015
28        29   ORD00029  20260222       C0001       P019      D020      3.0
29        30   ORD00030  20261111       C0014       P003      D027      1.0
30        31   ORD00031  20261121       C0130       P012      D078      2.0
31        32  ORD00032   20260301       C0250       P015      D062      2.0
32        33   ORD00033  20260315       C0053       P024      D044      2.0
33        34   ORD00034  20261221       C0083       P017      D003      2.0
34        35    ORD0000  20260317        C002       P003      D069      3.0

   unit_price discount_%     sales    cost  profit
0     83000.0       15.0   70550.0   56440   14110
1     54000.0        0.0  108000.0   86400   21600
2     97000.0        0.0  194000.0  155200   38800
3     49000.0        0.0  147000.0  117600   29400
4     49000.0       15.0  124950.0   99960   24990
5    151000.0       10.0  135900.0  108720   27180
6    115000.0        5.0  218500.0  174800   43700
7     89000.0        0.0   89000.0   71200   17800
8    105000.0       15.0  267750.0  214200   53550
9     88000.0        5.0  167200.0  133760   33440
10    52000.0       10.0  140400.0  112320   28080
11   135000.0       10.0  243000.0  194400   48600
12    95000.0       10.0   85500.0   68400   17100
13   127000.0       10.0  114300.0   91440   22860
14   105000.0       15.0  267750.0  214200   53550
15   131000.0        0.0  393000.0  314400   78600
16   124000.0       15.0  316200.0  252960   63240
17    44000.0       10.0   79200.0   63360   15840
18    49000.0       10.0   44100.0   35280    8820
19    92000.0        0.0  184000.0  147200   36800
20    77000.0       15.0   65450.0   52360   13090
21    87000.0       15.0  221850.0  177480   44370
22    61000.0        5.0   57950.0   46360   11590
23    65000.0       10.0  117000.0   93600   23400
24    89000.0       10.0  240300.0  192240   48060
25   121000.0        0.0  363000.0  290400   72600
26    92000.0       15.0  156400.0  125120   31280
27                                   39200    9800
28    85000.0        0.0  255000.0  204000   51000
29   110000.0       10.0   99000.0   79200   19800
30   120000.0        5.0  228000.0  182400   45600
31    88000.0        0.0  176000.0  140800   35200
32   103000.0        0.0  206000.0  164800   41200
33   136000.0       15.0  231200.0  184960   46240
34    68000.0       10.0  183600.0  146880   36720

In [179]:
columns = ["sales","discount_%","quantity","unit_price"]

for col in columns:
    df[col] = pd.to_numeric(df[col], errors= "coerce").astype("Int64")

In [180]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1236 entries, 0 to 1235
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sales_id     1236 non-null   int64
 1   order_id     1236 non-null   object
 2   date_id      1236 non-null   int64
 3   customer_id  1236 non-null   object
 4   product_id   1236 non-null   object
 5   dealer_id    1236 non-null   object
 6   quantity     1152 non-null   Int64
 7   unit_price   1152 non-null   Int64
 8   discount_%   1152 non-null   Int64
 9   sales        1152 non-null   Int64
 10  cost         1236 non-null   int64
 11  profit       1236 non-null   int64
dtypes: Int64(4), int64(4), object(4)
memory usage: 120.8+ KB

In [249]:
import pandas as pd 
df1 = pd.read_csv("Dim_Dealer_2026_csv.csv")

In [250]:
df1.info()
df1.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82 entries, 0 to 81
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Dealer_ID    82 non-null     object
 1   Dealer_Name  77 non-null     object
 2   Country      77 non-null     object
dtypes: object(3)
memory usage: 2.1+ KB

       Dealer_ID              Dealer_Name Country
count         82                       77      77
unique        80                       75      10
top         D045  Mercedes-Benz Dealer 45   Japan
freq           2                        2      14

In [251]:
df1.columns = df1.columns.str.lower()
print(df1.columns)

Index(['dealer_id', 'dealer_name', 'country'], dtype='object')

In [252]:
df1 = df1.dropna()

In [301]:
df1 = df1.replace({'D001x' : 'D041',
                   'Indi' : 'India'}
                 ).fillna('NA')

In [302]:
df1['dealer_name'] = df1['dealer_name'].str.strip().str.capitalize()
df1['dealer_name'] = df1['dealer_name'].replace('Mercedes-Benz Dealer', 'Mercedes-Benz Dealer 41')

In [303]:
print(df1.head(40))

   dealer_id              dealer_name  country
0       D001   Mercedes-benz dealer 1    India
1       D002   Mercedes-benz dealer 2    Japan
2       D003   Mercedes-benz dealer 3      UAE
3       D004   Mercedes-benz dealer 4      UAE
4       D005   Mercedes-benz dealer 5      UAE
5       D006   Mercedes-benz dealer 6    India
6       D007   Mercedes-benz dealer 7       UK
7       D008   Mercedes-benz dealer 8    India
8       D009   Mercedes-benz dealer 9      USA
9       D010  Mercedes-benz dealer 10  Germany
10      D011  Mercedes-benz dealer 11    Japan
11      D012  Mercedes-benz dealer 12    Japan
12      D013  Mercedes-benz dealer 13    India
13      D014  Mercedes-benz dealer 14    China
14      D015  Mercedes-benz dealer 15  Germany
15      D016  Mercedes-benz dealer 16    China
16      D017  Mercedes-benz dealer 17      USA
17      D018  Mercedes-benz dealer 18    China
18      D019  Mercedes-benz dealer 19       UK
19      D020  Mercedes-benz dealer 20  Germany
20      D021  Mercedes-benz dealer 21  Germany
21      D022  Mercedes-benz dealer 22    Japan
22      D023  Mercedes-benz dealer 23      UAE
23      D024  Mercedes-benz dealer 24    India
24      D025  Mercedes-benz dealer 25      UAE
25      D026  Mercedes-benz dealer 26      UAE
26      D027  Mercedes-benz dealer 27      USA
28      D029  Mercedes-benz dealer 29      UAE
29      D030  Mercedes-benz dealer 30      UAE
30      D031  Mercedes-benz dealer 31  Germany
32      D033  Mercedes-benz dealer 33      USA
33      D034  Mercedes-benz dealer 34  Germany
34      D035  Mercedes-benz dealer 35    China
35      D036  Mercedes-benz dealer 36      USA
36      D037  Mercedes-benz dealer 37    China
37      D038  Mercedes-benz dealer 38       UK
38      D039  Mercedes-benz dealer 39    China
39      D040  Mercedes-benz dealer 40      UAE
40      D041  Mercedes-benz dealer 41    India
41      D042  Mercedes-benz dealer 42    Japan

In [304]:
import pandas as pd
df2 = pd.read_csv("Dim_Customer_2026_csv.csv")
data = pd.DataFrame(df2)
df2.isnull().sum()

Customer_ID       0
Customer_Name    28
Gender           28
Age              28
Country          28
dtype: int64

In [305]:
df2.columns = df2.columns.str.lower()
print(df2.columns)

Index(['customer_id', 'customer_name', 'gender', 'age', 'country'], dtype='object')

In [306]:
df2['customer_id'] = df2['customer_id'].str.strip()

In [307]:
import numpy as np
df2 = df2.dropna()

In [308]:
df2.isnull().sum()

customer_id      0
customer_name    0
gender           0
age              0
country          0
dtype: int64

In [309]:
print(df2.head(35))

   customer_id customer_name  gender   age  country
0        C0001    Customer 1  Female  67.0    China
1        C0002    Customer 2  Female  64.0    India
2        C0003    Customer 3  Female  55.0       UK
3        C0004    Customer 4  Female  51.0       UK
4        C0005    Customer 5  Female  29.0    China
6        C0007   Customer 7    Male   35.0     USA
7        C0008    Customer 8    Male  53.0    China
8        C0009    Customer 9  Female  34.0    India
9        C0010   Customer 10  Female  52.0    Japan
10       C0011   Customer 11    Male  62.0    Japan
11       C0012   Customer 12    Male  25.0      USA
12       C0013   Customer 13  Female  26.0  Germany
13       C0014   Customer 14  Female  23.0  Germany
14       C0015   Customer 15  Female  69.0       UK
15       C0016   Customer 16    Male  48.0      USA
16       c0017   customer 17    male  25.0      uae
18       C0019   Customer 19  Female  62.0       UK
19       C0020   Customer 20  Female  47.0  Germany
20       C0021   Customer 21    Male  42.0  Germany
21       C0022   Customer 22  Female  34.0      USA
22       C0023   Customer 23  Female  22.0  Germany
23       C0024   Customer 24    Male  25.0    Japan
24       C0025   Customer 25  Female  53.0    China
25       C0026   CUSTOMER 26  FEMALE  45.0    JAPAN
26       C0027   Customer 27    Male  59.0       UK
27       C0028   Customer 28  Female  22.0       UK
28       C0029   Customer 29  Female  48.0      UAE
30       C0031   Customer 31  Female  28.0       UK
31       C0032   Customer 32    Male  47.0    China
32       C0033   CUSTOMER 33    MALE  53.0    CHINA
33       C0034   Customer 34  Female  54.0      UAE
34       C0035   Customer 35    Male  29.0    China
35       C0036   Customer 36  Female  70.0    India
36       C0037   Customer 37    Male  60.0       UK
37       C0038   Customer 38  Female  64.0  Germany

In [310]:
df2 = df2.replace({'MALE':'Male',
                   'male':'Male',
                   'FEMALE':'Female',
                   'female':'Female'}
                 ).fillna('NA')

In [311]:
cols = ['customer_id','customer_name','gender','country']

for col in cols:
    df2[col] = df2[col].astype(str).str.strip().str.capitalize()

In [312]:
print(df2.head(35))

   customer_id customer_name  gender   age  country
0        C0001    Customer 1  Female  67.0    China
1        C0002    Customer 2  Female  64.0    India
2        C0003    Customer 3  Female  55.0       Uk
3        C0004    Customer 4  Female  51.0       Uk
4        C0005    Customer 5  Female  29.0    China
6        C0007    Customer 7    Male  35.0      Usa
7        C0008    Customer 8    Male  53.0    China
8        C0009    Customer 9  Female  34.0    India
9        C0010   Customer 10  Female  52.0    Japan
10       C0011   Customer 11    Male  62.0    Japan
11       C0012   Customer 12    Male  25.0      Usa
12       C0013   Customer 13  Female  26.0  Germany
13       C0014   Customer 14  Female  23.0  Germany
14       C0015   Customer 15  Female  69.0       Uk
15       C0016   Customer 16    Male  48.0      Usa
16       C0017   Customer 17    Male  25.0      Uae
18       C0019   Customer 19  Female  62.0       Uk
19       C0020   Customer 20  Female  47.0  Germany
20       C0021   Customer 21    Male  42.0  Germany
21       C0022   Customer 22  Female  34.0      Usa
22       C0023   Customer 23  Female  22.0  Germany
23       C0024   Customer 24    Male  25.0    Japan
24       C0025   Customer 25  Female  53.0    China
25       C0026   Customer 26  Female  45.0    Japan
26       C0027   Customer 27    Male  59.0       Uk
27       C0028   Customer 28  Female  22.0       Uk
28       C0029   Customer 29  Female  48.0      Uae
30       C0031   Customer 31  Female  28.0       Uk
31       C0032   Customer 32    Male  47.0    China
32       C0033   Customer 33    Male  53.0    China
33       C0034   Customer 34  Female  54.0      Uae
34       C0035   Customer 35    Male  29.0    China
35       C0036   Customer 36  Female  70.0    India
36       C0037   Customer 37    Male  60.0       Uk
37       C0038   Customer 38  Female  64.0  Germany

In [313]:
print(df2.head(35))

   customer_id customer_name  gender   age  country
0        C0001    Customer 1  Female  67.0    China
1        C0002    Customer 2  Female  64.0    India
2        C0003    Customer 3  Female  55.0       Uk
3        C0004    Customer 4  Female  51.0       Uk
4        C0005    Customer 5  Female  29.0    China
6        C0007    Customer 7    Male  35.0      Usa
7        C0008    Customer 8    Male  53.0    China
8        C0009    Customer 9  Female  34.0    India
9        C0010   Customer 10  Female  52.0    Japan
10       C0011   Customer 11    Male  62.0    Japan
11       C0012   Customer 12    Male  25.0      Usa
12       C0013   Customer 13  Female  26.0  Germany
13       C0014   Customer 14  Female  23.0  Germany
14       C0015   Customer 15  Female  69.0       Uk
15       C0016   Customer 16    Male  48.0      Usa
16       C0017   Customer 17    Male  25.0      Uae
18       C0019   Customer 19  Female  62.0       Uk
19       C0020   Customer 20  Female  47.0  Germany
20       C0021   Customer 21    Male  42.0  Germany
21       C0022   Customer 22  Female  34.0      Usa
22       C0023   Customer 23  Female  22.0  Germany
23       C0024   Customer 24    Male  25.0    Japan
24       C0025   Customer 25  Female  53.0    China
25       C0026   Customer 26  Female  45.0    Japan
26       C0027   Customer 27    Male  59.0       Uk
27       C0028   Customer 28  Female  22.0       Uk
28       C0029   Customer 29  Female  48.0      Uae
30       C0031   Customer 31  Female  28.0       Uk
31       C0032   Customer 32    Male  47.0    China
32       C0033   Customer 33    Male  53.0    China
33       C0034   Customer 34  Female  54.0      Uae
34       C0035   Customer 35    Male  29.0    China
35       C0036   Customer 36  Female  70.0    India
36       C0037   Customer 37    Male  60.0       Uk
37       C0038   Customer 38  Female  64.0  Germany

In [314]:
df2['age']= pd.to_numeric(df2['age'],errors= 'coerce').astype('Int64')

In [315]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 384 entries, 0 to 411
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    384 non-null    object
 1   customer_name  384 non-null    object
 2   gender         384 non-null    object
 3   age            384 non-null    Int64
 4   country        384 non-null    object
dtypes: Int64(1), object(4)
memory usage: 18.4+ KB

In [316]:
print(df2.head(35))

   customer_id customer_name  gender  age  country
0        C0001    Customer 1  Female   67    China
1        C0002    Customer 2  Female   64    India
2        C0003    Customer 3  Female   55       Uk
3        C0004    Customer 4  Female   51       Uk
4        C0005    Customer 5  Female   29    China
6        C0007    Customer 7    Male   35      Usa
7        C0008    Customer 8    Male   53    China
8        C0009    Customer 9  Female   34    India
9        C0010   Customer 10  Female   52    Japan
10       C0011   Customer 11    Male   62    Japan
11       C0012   Customer 12    Male   25      Usa
12       C0013   Customer 13  Female   26  Germany
13       C0014   Customer 14  Female   23  Germany
14       C0015   Customer 15  Female   69       Uk
15       C0016   Customer 16    Male   48      Usa
16       C0017   Customer 17    Male   25      Uae
18       C0019   Customer 19  Female   62       Uk
19       C0020   Customer 20  Female   47  Germany
20       C0021   Customer 21    Male   42  Germany
21       C0022   Customer 22  Female   34      Usa
22       C0023   Customer 23  Female   22  Germany
23       C0024   Customer 24    Male   25    Japan
24       C0025   Customer 25  Female   53    China
25       C0026   Customer 26  Female   45    Japan
26       C0027   Customer 27    Male   59       Uk
27       C0028   Customer 28  Female   22       Uk
28       C0029   Customer 29  Female   48      Uae
30       C0031   Customer 31  Female   28       Uk
31       C0032   Customer 32    Male   47    China
32       C0033   Customer 33    Male   53    China
33       C0034   Customer 34  Female   54      Uae
34       C0035   Customer 35    Male   29    China
35       C0036   Customer 36  Female   70    India
36       C0037   Customer 37    Male   60       Uk
37       C0038   Customer 38  Female   64  Germany

In [317]:
labels = ['Young', 'Young-adult', 'Senior','Senior-aged']
df2['age_group'] = pd.qcut(df2['age'], q=4, labels = labels)

In [318]:
print(df2)

    customer_id customer_name  gender  age country    age_group
0         C0001    Customer 1  Female   67   China  Senior-aged
1         C0002    Customer 2  Female   64   India  Senior-aged
2         C0003    Customer 3  Female   55      Uk       Senior
3         C0004    Customer 4  Female   51      Uk       Senior
4         C0005    Customer 5  Female   29   China        Young
..          ...           ...     ...  ...     ...          ...
407       C0182  Customer 182    Male   40     Uae  Young-adult
408       C0005    Customer 5  Female   29   China        Young
409       C0112  Customer 112    Male   41      Uk  Young-adult
410       C0067   Customer 67    Male   53   Japan       Senior
411       C0009    Customer 9  Female   34   India        Young

[384 rows x 6 columns]

In [319]:
import pandas as pd 
df3 = pd.read_csv("Dim_Product_2026.csv")
data = pd.DataFrame(df3)

In [320]:
df3

   Product_ID           Model_Name Category Fuel_Type    MSRP
0        P001              A-Class   Sports  Electric   49000
1        P002              C-Class    Sedan    Diesel   59000
2        P003                  CLA   Sports    Diesel  132000
3        P004                  CLE       EV  Electric  161000
4        P005              E-Class       EV    Hybrid  134000
5        P006              S-Class      SUV    Diesel   83000
6        P007                  GLA    Sedan    Diesel  175000
7        P008                  GLB      SUV  Electric  126000
8        P009                  GLC    Sedan    Diesel   76000
9        P010                  GLE   Sports    Diesel  124000
10       P011                  GLS       EV    Hybrid   61000
11       P012              G-Class       EV    Diesel  141000
12       P013                  EQA    Sedan  Electric   96000
13       P014                  EQB      Van  Electric   43000
14       P015                  EQE      Van  Electric   40000
15       P016                  EQS    Sedan    Diesel  143000
16       P017               AMG GT       EV    Diesel   46000
17       P018                   SL   Sports    Petrol  158000
18       P019      Maybach S-Class      Van    Petrol  103000
19       P020     Mercedes-AMG C63      Van    Hybrid   94000
20       P021  Mercedes-AMG GLE 53    Sedan    Hybrid   48000
21       P022           CLA 45 AMG    Sedan    Petrol  164000
22       P023              EQS SUV   Sports    Diesel  142000
23       P024              V-Class      SUV  Electric  108000
24       P025             Sprinter       EV  Electric   81000
25       P026        C-Class Coupe      SUV    Petrol  125000
26       P027    E-Class Cabriolet   Sports  Electric   89000
27       P028            GLC Coupe       EV    Hybrid   52000
28       P029            GLE Coupe   Sports    Hybrid  169000
29       P030              EQE SUV    Sedan    Petrol  125000

In [321]:
df3.columns = df3.columns.str.lower()
print(df3.columns)

Index(['product_id', 'model_name', 'category', 'fuel_type', 'msrp'], dtype='object')

In [322]:
df4 = pd.read_csv("Dim_Date_2026.csv", parse_dates = ["Date"])
data = pd.DataFrame(df4)
df4

      Date_ID       Date  Day  Month Month_Name Quarter  Year
0    20260101 2026-01-01    1      1    January      Q1  2026
1    20260102 2026-01-02    2      1    January      Q1  2026
2    20260103 2026-01-03    3      1    January      Q1  2026
3    20260104 2026-01-04    4      1    January      Q1  2026
4    20260105 2026-01-05    5      1    January      Q1  2026
..        ...        ...  ...    ...        ...     ...   ...
360  20261227 2026-12-27   27     12   December      Q4  2026
361  20261228 2026-12-28   28     12   December      Q4  2026
362  20261229 2026-12-29   29     12   December      Q4  2026
363  20261230 2026-12-30   30     12   December      Q4  2026
364  20261231 2026-12-31   31     12   December      Q4  2026

[365 rows x 7 columns]

In [323]:
df4.columns = df4.columns.str.lower()
print(df4.columns)

Index(['date_id', 'date', 'day', 'month', 'month_name', 'quarter', 'year'], dtype='object')

In [324]:
data1 = pd.merge(df,df1,on= 'dealer_id')
data2 = pd.merge(df,df2,on= 'customer_id')
data3 = pd.merge(df,df3,on= 'product_id')
data4 = pd.merge(df,df4, on = 'date_id')

In [325]:
gender_wise_sale = data2.groupby('gender')['sales'].sum()

In [326]:
print(gender_wise_sale)

gender
Female    95342150
Male      90912200
Name: sales, dtype: Int64

In [ ]:
country_wise_sale = data1.groupby('country')['sales'].sum()
print(country_wise_sale)

In [ ]:
agegroup_wise_sale = data2.groupby('age_group')['sales'].sum()
print(agegroup_wise_sale)

In [ ]:
month_order = [
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'
]

Month_wise_sales = (
    data4.groupby('month_name')['sales'].sum().reindex(month_order))

print(Month_wise_sales)

In [ ]:
quarter_wise_sales = data4.groupby('quarter')['sales'].sum()
print(quarter_wise_sales)

In [328]:
category_wise_sales = data3.groupby('category')['sales'].sum()
print(category_wise_sales)

category
EV        44641800
SUV       26735350
Sedan     54603850
Sports    54456700
Van       25882750
Name: sales, dtype: Int64

In [329]:
category_wise_profit = (data3.groupby('category')['profit'].sum() / data1['profit'].sum() * 100).round(2)
print(category_wise_profit)

category
EV        22.82
SUV       14.12
Sedan     28.59
Sports    27.93
Van       13.34
Name: profit, dtype: float64

In [330]:
fuel_wise_profit = (data3.groupby('fuel_type')['profit'].sum() / data1['profit'].sum() * 100).round(2)
print(fuel_wise_profit)

fuel_type
Diesel      37.00
Electric    31.83
Hybrid      20.70
Petrol      17.28
Name: profit, dtype: float64

In [332]:
model_wise_sales = data3.groupby('model_name')['sales'].sum()
print(model_wise_sales)

model_name
A-Class                7369800
AMG GT                 8843200
C-Class                6063850
C-Class Coupe          8893450
CLA                    9017350
CLA 45 AMG             6508350
CLE                    6184350
E-Class                6544500
E-Class Cabriolet      8850600
EQA                    7149750
EQB                    6982150
EQE                    7342400
EQE SUV                5475700
EQS                    8446750
EQS SUV                9192600
G-Class                3994600
GLA                    8304400
GLB                    5224450
GLC                    5702150
GLC Coupe              6716200
GLE                    5606500
GLE Coupe              8620200
GLS                    6545500
Maybach S-Class        5483700
Mercedes-AMG C63       6074500
Mercedes-AMG GLE 53    6952900
S-Class                6278450
SL                     5799650
Sprinter               5813450
V-Class                6339000
Name: sales, dtype: Int64

In [334]:
from sqlalchemy import create_engine

username= "root"
password= "devanssaini"
host = "localhost"
port="3306"
database="benz" 

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")
table_name = "sales"
df.to_sql(table_name, engine, if_exists = "replace", index= False)
pd.read_sql("select * from sales LIMIT 5;", engine)

,sales_id,order_id,date_id,customer_id,product_id,dealer_id,quantity,unit_price,discount_%,sales,cost,profit
0,1,ORD00001,20261130,C0025,P003,D069,1,83000,15,70550,56440,14110
1,2,ORD00002,20260917,C0110,P002,D012,2,54000,0,108000,86400,21600
2,3,ORD00003,20260504,C0047,P018,D055,2,97000,0,194000,155200,38800
3,4,ORD00004,20260425,C0323,P021,D075,3,49000,0,147000,117600,29400
4,5,ORD00005,20260126,C0114,P002,D072,3,49000,15,124950,99960,24990

In [335]:
from sqlalchemy import create_engine

username= "root"
password= "devanssaini"
host = "localhost"
port="3306"
database="benz" 

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")
table_name = "dealer"
df1.to_sql(table_name, engine, if_exists = "replace", index= False)
pd.read_sql("select * from dealer LIMIT 5;", engine)

  dealer_id             dealer_name country
0      D001  Mercedes-benz dealer 1   India
1      D002  Mercedes-benz dealer 2   Japan
2      D003  Mercedes-benz dealer 3     UAE
3      D004  Mercedes-benz dealer 4     UAE
4      D005  Mercedes-benz dealer 5     UAE

In [336]:
from sqlalchemy import create_engine

username= "root"
password= "devanssaini"
host = "localhost"
port="3306"
database="benz" 

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")
table_name = "customers"
df2.to_sql(table_name, engine, if_exists = "replace", index= False)
pd.read_sql("select * from customers LIMIT 5;", engine)

  customer_id customer_name  gender  age country    age_group
0       C0001    Customer 1  Female   67   China  Senior-aged
1       C0002    Customer 2  Female   64   India  Senior-aged
2       C0003    Customer 3  Female   55      Uk       Senior
3       C0004    Customer 4  Female   51      Uk       Senior
4       C0005    Customer 5  Female   29   China        Young

In [337]:
from sqlalchemy import create_engine

username= "root"
password= "devanssaini"
host = "localhost"
port="3306"
database="benz" 

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")
table_name = "product"
df3.to_sql(table_name, engine, if_exists = "replace", index= False)
pd.read_sql("select * from product LIMIT 5;", engine)

  product_id model_name category fuel_type    msrp
0       P001    A-Class   Sports  Electric   49000
1       P002    C-Class    Sedan    Diesel   59000
2       P003        CLA   Sports    Diesel  132000
3       P004        CLE       EV  Electric  161000
4       P005    E-Class       EV    Hybrid  134000

In [338]:
from sqlalchemy import create_engine

username= "root"
password= "devanssaini"
host = "localhost"
port="3306"
database="benz" 

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")
table_name = "date"
df4.to_sql(table_name, engine, if_exists = "replace", index= False)
pd.read_sql("select * from date LIMIT 5;", engine)

    date_id       date  day  month month_name quarter  year
0  20260101 2026-01-01    1      1    January      Q1  2026
1  20260102 2026-01-02    2      1    January      Q1  2026
2  20260103 2026-01-03    3      1    January      Q1  2026
3  20260104 2026-01-04    4      1    January      Q1  2026
4  20260105 2026-01-05    5      1    January      Q1  2026

In [339]:
print(df)

      sales_id  order_id   date_id customer_id product_id dealer_id  quantity  \
0            1  ORD00001  20261130       C0025       P003      D069         1
1            2  ORD00002  20260917       C0110       P002      D012         2
2            3  ORD00003  20260504       C0047       P018      D055         2
3            4  ORD00004  20260425       C0323       P021      D075         3
4            5  ORD00005  20260126       C0114       P002      D072         3
...        ...       ...       ...         ...        ...       ...       ...
1231      1107  ORD01107  20260922       C0189       P023      D022         3
1232      1019  ORD01019  20260424       C0083       P030      D079         2
1233       268  ORD00268  20260604       C0387       P023      D080         1
1234       721  ORD00721  20260913       C0164       P029      D065         2
1235      1134  ORD01134  20260919       C0127       P005      D040         2

      unit_price  discount_%   sales    cost  profit
0          83000          15   70550   56440   14110
1          54000           0  108000   86400   21600
2          97000           0  194000  155200   38800
3          49000           0  147000  117600   29400
4          49000          15  124950   99960   24990
...          ...         ...     ...     ...     ...
1231       79000          10  213300  170640   42660
1232       74000           0  148000  118400   29600
1233      106000          10   95400   76320   19080
1234      154000          10  277200  221760   55440
1235       70000          10  126000  100800   25200

[1236 rows x 12 columns]

In [340]:
print(df1)

   dealer_id              dealer_name country
0       D001   Mercedes-benz dealer 1   India
1       D002   Mercedes-benz dealer 2   Japan
2       D003   Mercedes-benz dealer 3     UAE
3       D004   Mercedes-benz dealer 4     UAE
4       D005   Mercedes-benz dealer 5     UAE
..       ...                      ...     ...
77      D078  Mercedes-benz dealer 78   Japan
78      D079  Mercedes-benz dealer 79      UK
79      D080  Mercedes-benz dealer 80   Japan
80      D024  Mercedes-benz dealer 24   India
81      D045  Mercedes-benz dealer 45     USA

[77 rows x 3 columns]

In [341]:
print(df2)

    customer_id customer_name  gender  age country    age_group
0         C0001    Customer 1  Female   67   China  Senior-aged
1         C0002    Customer 2  Female   64   India  Senior-aged
2         C0003    Customer 3  Female   55      Uk       Senior
3         C0004    Customer 4  Female   51      Uk       Senior
4         C0005    Customer 5  Female   29   China        Young
..          ...           ...     ...  ...     ...          ...
407       C0182  Customer 182    Male   40     Uae  Young-adult
408       C0005    Customer 5  Female   29   China        Young
409       C0112  Customer 112    Male   41      Uk  Young-adult
410       C0067   Customer 67    Male   53   Japan       Senior
411       C0009    Customer 9  Female   34   India        Young

[384 rows x 6 columns]

In [342]:
print(df3)

   product_id           model_name category fuel_type    msrp
0        P001              A-Class   Sports  Electric   49000
1        P002              C-Class    Sedan    Diesel   59000
2        P003                  CLA   Sports    Diesel  132000
3        P004                  CLE       EV  Electric  161000
4        P005              E-Class       EV    Hybrid  134000
5        P006              S-Class      SUV    Diesel   83000
6        P007                  GLA    Sedan    Diesel  175000
7        P008                  GLB      SUV  Electric  126000
8        P009                  GLC    Sedan    Diesel   76000
9        P010                  GLE   Sports    Diesel  124000
10       P011                  GLS       EV    Hybrid   61000
11       P012              G-Class       EV    Diesel  141000
12       P013                  EQA    Sedan  Electric   96000
13       P014                  EQB      Van  Electric   43000
14       P015                  EQE      Van  Electric   40000
15       P016                  EQS    Sedan    Diesel  143000
16       P017               AMG GT       EV    Diesel   46000
17       P018                   SL   Sports    Petrol  158000
18       P019      Maybach S-Class      Van    Petrol  103000
19       P020     Mercedes-AMG C63      Van    Hybrid   94000
20       P021  Mercedes-AMG GLE 53    Sedan    Hybrid   48000
21       P022           CLA 45 AMG    Sedan    Petrol  164000
22       P023              EQS SUV   Sports    Diesel  142000
23       P024              V-Class      SUV  Electric  108000
24       P025             Sprinter       EV  Electric   81000
25       P026        C-Class Coupe      SUV    Petrol  125000
26       P027    E-Class Cabriolet   Sports  Electric   89000
27       P028            GLC Coupe       EV    Hybrid   52000
28       P029            GLE Coupe   Sports    Hybrid  169000
29       P030              EQE SUV    Sedan    Petrol  125000

In [343]:
print(df4)

      date_id       date  day  month month_name quarter  year
0    20260101 2026-01-01    1      1    January      Q1  2026
1    20260102 2026-01-02    2      1    January      Q1  2026
2    20260103 2026-01-03    3      1    January      Q1  2026
3    20260104 2026-01-04    4      1    January      Q1  2026
4    20260105 2026-01-05    5      1    January      Q1  2026
..        ...        ...  ...    ...        ...     ...   ...
360  20261227 2026-12-27   27     12   December      Q4  2026
361  20261228 2026-12-28   28     12   December      Q4  2026
362  20261229 2026-12-29   29     12   December      Q4  2026
363  20261230 2026-12-30   30     12   December      Q4  2026
364  20261231 2026-12-31   31     12   December      Q4  2026

[365 rows x 7 columns]